package com.sushimei.sushimei.backend.order;

public enum OrderLifecycleError {
    ORDER_NOT_FOUND,
    ORDER_INVALID_TRANSITION,
    ORDER_PAYMENT_NOT_VALIDATABLE,
    ORDER_PAYMENT_COLLECTION_REQUIRED,
    ORDER_PAYMENT_COLLECTION_NOT_SUPPORTED,
    ORDER_INVALID_PAYMENT_COLLECTION_REQUEST,
    ORDER_PAYMENT_COLLECTION_BUSINESS_DAY_NOT_OPEN,
    ORDER_OPERATION_NOT_SUPPORTED,
    ORDER_INVALID_VOID_REQUEST
}
