package com.sushimei.sushimei.backend.checkout;

public enum InvalidCartItemReason {
    MISSING_CART_ID,
    MISSING_ITEM_ID,
    INVALID_DISH_NAME,
    INVALID_QUANTITY,
    INVALID_UNIT_PRICE,
    MISSING_MONETARY_REPRESENTATIONS,
    INVALID_NUMERIC_UNIT_PRICE,
    INVALID_LEGACY_UNIT_PRICE,
    UNIT_PRICE_REPRESENTATIONS_DISAGREE,
    LINE_TOTAL_OVERFLOW,
    CART_TOTAL_OVERFLOW
}
