package com.sushimei.sushimei.backend.pos;

public enum ManualPosOrderError {
    ORDER_INVALID,
    ORDER_IDEMPOTENCY_CONFLICT,
    ORDER_MENU_ITEM_NOT_FOUND,
    ORDER_MENU_ITEM_UNAVAILABLE,
    ORDER_CONFIGURATION_INVALID,
    ORDER_PROMOTION_CONFLICT,
    ORDER_FORBIDDEN_OPERATION
}
