package com.cardovia.merkon.backend.security;

public enum SecurityAuditEventType {
    LOGIN_SUCCESS, LOGIN_FAILURE, REFRESH_SUCCESS, REFRESH_FAILURE, REFRESH_REPLAY_DETECTED,
    LOGOUT, SESSION_REVOKED, USER_CREATED, USER_UPDATED, USER_DISABLED, PASSWORD_CHANGED, PASSWORD_RESET,
    REGISTRATION_ACCEPTED, REGISTRATION_REJECTED,
    EMAIL_VERIFICATION_SEND_SUCCEEDED, EMAIL_VERIFICATION_SEND_FAILED,
    EMAIL_VERIFICATION_RESEND_ACCEPTED, EMAIL_VERIFICATION_RESEND_REJECTED,
    EMAIL_VERIFICATION_SUCCEEDED, EMAIL_VERIFICATION_REJECTED,
    PASSWORD_RECOVERY_REQUEST_ACCEPTED, PASSWORD_RECOVERY_REQUEST_REJECTED,
    PASSWORD_RECOVERY_SEND_SUCCEEDED, PASSWORD_RECOVERY_SEND_FAILED,
    PASSWORD_RECOVERY_COMPLETED, PASSWORD_RECOVERY_REJECTED
}
