spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sushidb
    username: sushi
    password: mei
  jpa:
    hibernate:
      ddl-auto: update # Ideal para desarrollo, crea las tablas automáticamente
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3.1
      temperature: 0.3
    embedding-model:
      base-url: http://localhost:11434
      model-name: nomic-embed-text

whatsapp:
  api:
    token: ""
    phone-number-id: "1320287381159448" # El identificador del número de prueba

server:
  address: 0.0.0.0

ai:

  provider: gemini

  gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash

  ollama:
    base-url: http://localhost:11434
    model: llama3.1