package com.sushimei.sushimei.backend.catalog;

public enum CatalogDomainError {
    MENU_ITEM_NOT_ORDERABLE,
    MENU_ITEM_UNAVAILABLE,
    CATALOG_TAG_NOT_FOUND,
    CATALOG_TAG_VERSION_CONFLICT,
    MENU_SELECTION_GROUP_NOT_FOUND,
    MENU_SELECTION_GROUP_VERSION_CONFLICT,
    MENU_SELECTION_RULE_NOT_FOUND,
    MENU_SELECTION_RULE_VERSION_CONFLICT,
    MENU_CONFIGURATION_INCOMPLETE,
    MENU_SELECTION_NOT_ALLOWED,
    MENU_SELECTION_DUPLICATE_NOT_ALLOWED,
    MENU_CONFIGURATION_CYCLE,
    MENU_CONFIGURATION_INVALID
}
