CREATE TABLE public.cart (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number varchar(255),
    status varchar(255),
    CONSTRAINT cart_pkey PRIMARY KEY (id)
);

CREATE TABLE public.cart_items (
    quantity integer,
    unit_price double precision,
    cart_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dish_name varchar(255),
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE public.carts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status varchar(255),
    CONSTRAINT carts_pkey PRIMARY KEY (id)
);

CREATE TABLE public.conversation_sessions (
    phone_number varchar(32) NOT NULL,
    cash_denomination numeric(19,2),
    created_at timestamp(6) with time zone NOT NULL,
    delivery_address varchar(500),
    fulfillment_type varchar(16),
    last_activity_at timestamp(6) with time zone NOT NULL,
    payment_method varchar(16),
    pickup_name varchar(120),
    state varchar(48) NOT NULL,
    transfer_receipt_path varchar(1024),
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT conversation_sessions_pkey PRIMARY KEY (phone_number),
    CONSTRAINT conversation_sessions_fulfillment_type_check
        CHECK (fulfillment_type IN ('DELIVERY', 'PICKUP')),
    CONSTRAINT conversation_sessions_payment_method_check
        CHECK (payment_method IN ('CASH', 'TRANSFER', 'CARD')),
    CONSTRAINT conversation_sessions_state_check
        CHECK (state IN (
            'ORDERING',
            'WAITING_CART_CONFIRMATION',
            'WAITING_FULFILLMENT_TYPE',
            'WAITING_DELIVERY_ADDRESS',
            'WAITING_PICKUP_NAME',
            'WAITING_PAYMENT_METHOD',
            'WAITING_CASH_DENOMINATION',
            'WAITING_TRANSFER_RECEIPT',
            'READY_TO_CONFIRM',
            'ORDER_CONFIRMED',
            'CANCELLED'
        ))
);

CREATE TABLE public.orders (
    total_amount double precision,
    created_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_address varchar(500),
    delivery_type varchar(255),
    order_details text,
    payment_notes varchar(255),
    phone_number varchar(255),
    status varchar(255),
    transfer_receipt_path varchar(255),
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

ALTER TABLE public.cart_items
    ADD CONSTRAINT fk99e0am9jpriwxcm6is7xfedy3
    FOREIGN KEY (cart_id) REFERENCES public.cart(id);
