ALTER TABLE public.orders ADD COLUMN client_request_id uuid;
ALTER TABLE public.orders ADD COLUMN created_by_user_id bigint;
ALTER TABLE public.orders ADD COLUMN request_fingerprint varchar(64);

ALTER TABLE public.orders ADD CONSTRAINT orders_client_request_id_key UNIQUE (client_request_id);
ALTER TABLE public.orders ADD CONSTRAINT orders_created_by_user_id_fkey
    FOREIGN KEY (created_by_user_id) REFERENCES public.app_users(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_request_fingerprint_length_check
    CHECK (request_fingerprint IS NULL OR char_length(request_fingerprint) = 64);

ALTER TABLE public.order_lines ALTER COLUMN source_cart_item_id DROP NOT NULL;
ALTER TABLE public.order_lines ADD COLUMN source_menu_item_id bigint;
ALTER TABLE public.order_lines ADD COLUMN client_line_key varchar(120);
ALTER TABLE public.order_lines ADD COLUMN line_kind varchar(32) NOT NULL DEFAULT 'PAID';
ALTER TABLE public.order_lines ADD COLUMN catalog_base_unit_price numeric(19,2);
ALTER TABLE public.order_lines ADD COLUMN charged_base_unit_price numeric(19,2);
ALTER TABLE public.order_lines ADD COLUMN configuration_adjustment_amount numeric(19,2);
ALTER TABLE public.order_lines ADD COLUMN applied_promotion_id bigint;
ALTER TABLE public.order_lines ADD COLUMN applied_promotion_name varchar(160);
ALTER TABLE public.order_lines ADD COLUMN applied_promotion_benefit_type varchar(32);
ALTER TABLE public.order_lines ADD COLUMN reward_ordinal integer;
ALTER TABLE public.order_lines ADD COLUMN source_paid_line_id bigint;
ALTER TABLE public.order_lines DROP CONSTRAINT order_lines_unit_price_amount_positive_check;
ALTER TABLE public.order_lines DROP CONSTRAINT order_lines_line_total_amount_positive_check;
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_line_kind_check
    CHECK (line_kind IN ('PAID', 'PROMOTION_REWARD'));
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_money_by_kind_check
    CHECK (
        (line_kind = 'PAID' AND unit_price_amount > 0 AND line_total_amount > 0)
        OR
        (line_kind = 'PROMOTION_REWARD' AND unit_price_amount >= 0 AND line_total_amount >= 0)
    );
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_configuration_adjustment_nonnegative_check
    CHECK (configuration_adjustment_amount IS NULL OR configuration_adjustment_amount >= 0);
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_promotion_benefit_type_check
    CHECK (applied_promotion_benefit_type IS NULL
           OR applied_promotion_benefit_type IN ('FIXED_UNIT_PRICE', 'BUY_X_GET_Y_SAME_ITEM'));
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_reward_shape_check
    CHECK (
        (line_kind = 'PAID' AND source_paid_line_id IS NULL AND reward_ordinal IS NULL)
        OR
        (line_kind = 'PROMOTION_REWARD' AND source_paid_line_id IS NOT NULL AND reward_ordinal > 0)
    );
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_provenance_check
    CHECK (
        (line_kind = 'PAID' AND (source_cart_item_id IS NOT NULL OR source_menu_item_id IS NOT NULL))
        OR
        (line_kind = 'PROMOTION_REWARD' AND source_cart_item_id IS NULL AND source_menu_item_id IS NOT NULL)
    );
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_manual_pricing_evidence_check
    CHECK (
        source_menu_item_id IS NULL
        OR (catalog_base_unit_price IS NOT NULL
            AND charged_base_unit_price IS NOT NULL
            AND configuration_adjustment_amount IS NOT NULL)
    );
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_manual_client_line_key_check
    CHECK (
        (line_kind = 'PAID' AND source_menu_item_id IS NOT NULL
            AND client_line_key IS NOT NULL AND trim(client_line_key) <> '')
        OR
        (line_kind = 'PAID' AND source_menu_item_id IS NULL AND client_line_key IS NULL)
        OR
        (line_kind = 'PROMOTION_REWARD' AND client_line_key IS NULL)
    );
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_source_paid_line_fkey
    FOREIGN KEY (source_paid_line_id) REFERENCES public.order_lines(id);
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_source_paid_line_reward_ordinal_key
    UNIQUE (source_paid_line_id, reward_ordinal);
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_order_client_line_key_key
    UNIQUE (order_id, client_line_key);

CREATE TABLE public.order_line_selection_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_line_id bigint NOT NULL,
    parent_selection_snapshot_id bigint,
    group_id bigint NOT NULL,
    group_name varchar(160) NOT NULL,
    selection_position integer NOT NULL,
    selected_menu_item_id bigint NOT NULL,
    selected_item_name varchar(160) NOT NULL,
    quantity integer NOT NULL,
    catalog_unit_price numeric(19,2) NOT NULL,
    price_adjustment_amount numeric(19,2) NOT NULL,
    CONSTRAINT order_line_selection_snapshots_pkey PRIMARY KEY (id),
    CONSTRAINT order_line_selection_snapshots_order_line_fkey
        FOREIGN KEY (order_line_id) REFERENCES public.order_lines(id),
    CONSTRAINT order_line_selection_snapshots_parent_fkey
        FOREIGN KEY (parent_selection_snapshot_id) REFERENCES public.order_line_selection_snapshots(id),
    CONSTRAINT order_line_selection_snapshots_group_name_not_blank_check
        CHECK (trim(group_name) <> ''),
    CONSTRAINT order_line_selection_snapshots_item_name_not_blank_check
        CHECK (trim(selected_item_name) <> ''),
    CONSTRAINT order_line_selection_snapshots_position_positive_check CHECK (selection_position > 0),
    CONSTRAINT order_line_selection_snapshots_quantity_positive_check CHECK (quantity > 0),
    CONSTRAINT order_line_selection_snapshots_catalog_price_positive_check CHECK (catalog_unit_price > 0),
    CONSTRAINT order_line_selection_snapshots_adjustment_nonnegative_check CHECK (price_adjustment_amount >= 0)
);

CREATE INDEX order_line_selection_snapshots_order_line_idx
    ON public.order_line_selection_snapshots (order_line_id);
