CREATE TABLE public.business_days (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_date date NOT NULL,
    status varchar(16) NOT NULL,
    opening_cash_amount numeric(19,2) NOT NULL,
    opened_at timestamp with time zone NOT NULL,
    opened_by_user_id bigint NOT NULL,
    completed_sales_amount numeric(19,2),
    cash_sales_amount numeric(19,2),
    transfer_sales_amount numeric(19,2),
    card_sales_amount numeric(19,2),
    unclassified_sales_amount numeric(19,2),
    completed_order_count bigint,
    voided_order_count bigint,
    expected_closing_cash_amount numeric(19,2),
    actual_closing_cash_amount numeric(19,2),
    cash_difference_amount numeric(19,2),
    closed_at timestamp with time zone,
    closed_by_user_id bigint,
    open_guard integer,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT business_days_pkey PRIMARY KEY (id),
    CONSTRAINT business_days_business_date_key UNIQUE (business_date),
    CONSTRAINT business_days_open_guard_key UNIQUE (open_guard),
    CONSTRAINT business_days_opened_by_user_id_fkey
        FOREIGN KEY (opened_by_user_id) REFERENCES public.app_users(id),
    CONSTRAINT business_days_closed_by_user_id_fkey
        FOREIGN KEY (closed_by_user_id) REFERENCES public.app_users(id),
    CONSTRAINT business_days_status_check CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT business_days_opening_cash_nonnegative_check CHECK (opening_cash_amount >= 0),
    CONSTRAINT business_days_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT business_days_open_guard_status_check CHECK (
        (status = 'OPEN' AND open_guard = 1)
        OR (status = 'CLOSED' AND open_guard IS NULL)
    ),
    CONSTRAINT business_days_close_snapshot_check CHECK (
        (status = 'OPEN'
            AND completed_sales_amount IS NULL
            AND cash_sales_amount IS NULL
            AND transfer_sales_amount IS NULL
            AND card_sales_amount IS NULL
            AND unclassified_sales_amount IS NULL
            AND completed_order_count IS NULL
            AND voided_order_count IS NULL
            AND expected_closing_cash_amount IS NULL
            AND actual_closing_cash_amount IS NULL
            AND cash_difference_amount IS NULL
            AND closed_at IS NULL
            AND closed_by_user_id IS NULL)
        OR
        (status = 'CLOSED'
            AND completed_sales_amount IS NOT NULL AND completed_sales_amount >= 0
            AND cash_sales_amount IS NOT NULL AND cash_sales_amount >= 0
            AND transfer_sales_amount IS NOT NULL AND transfer_sales_amount >= 0
            AND card_sales_amount IS NOT NULL AND card_sales_amount >= 0
            AND unclassified_sales_amount IS NOT NULL AND unclassified_sales_amount >= 0
            AND completed_order_count IS NOT NULL AND completed_order_count >= 0
            AND voided_order_count IS NOT NULL AND voided_order_count >= 0
            AND expected_closing_cash_amount IS NOT NULL AND expected_closing_cash_amount >= 0
            AND actual_closing_cash_amount IS NOT NULL AND actual_closing_cash_amount >= 0
            AND cash_difference_amount IS NOT NULL
            AND closed_at IS NOT NULL
            AND closed_by_user_id IS NOT NULL
            AND completed_sales_amount = cash_sales_amount + transfer_sales_amount
                + card_sales_amount + unclassified_sales_amount
            AND expected_closing_cash_amount = opening_cash_amount + cash_sales_amount
            AND cash_difference_amount = actual_closing_cash_amount - expected_closing_cash_amount
            AND closed_at >= opened_at)
    )
);

CREATE TABLE public.business_day_operation_locks (
    lock_key integer NOT NULL,
    CONSTRAINT business_day_operation_locks_pkey PRIMARY KEY (lock_key),
    CONSTRAINT business_day_operation_locks_key_check CHECK (lock_key = 1)
);

INSERT INTO public.business_day_operation_locks (lock_key) VALUES (1);
