ALTER TABLE public.order_lines DROP CONSTRAINT order_lines_line_kind_check;
ALTER TABLE public.order_lines DROP CONSTRAINT order_lines_money_by_kind_check;
ALTER TABLE public.order_lines DROP CONSTRAINT order_lines_provenance_check;
ALTER TABLE public.order_lines DROP CONSTRAINT order_lines_reward_shape_check;
ALTER TABLE public.order_lines DROP CONSTRAINT order_lines_manual_client_line_key_check;

ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_line_kind_check
        CHECK (line_kind IN ('PAID', 'PROMOTION_REWARD', 'OPEN_SALE', 'MANUAL_PRICED_LINE'));
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_money_by_kind_check
        CHECK (
            (external_historical AND line_kind = 'PAID'
                AND unit_price_amount >= 0 AND line_total_amount >= 0)
            OR
            (NOT external_historical AND line_kind IN ('PAID', 'OPEN_SALE', 'MANUAL_PRICED_LINE')
                AND unit_price_amount > 0 AND line_total_amount > 0)
            OR
            (NOT external_historical AND line_kind = 'PROMOTION_REWARD'
                AND unit_price_amount >= 0 AND line_total_amount >= 0)
        );
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_provenance_check
        CHECK (
            (line_kind = 'PAID' AND (
                source_cart_item_id IS NOT NULL
                OR source_menu_item_id IS NOT NULL
                OR (external_product_reference IS NOT NULL AND trim(external_product_reference) <> '')
                OR external_historical
            ))
            OR
            (line_kind = 'PROMOTION_REWARD'
                AND applied_promotion_id IS NOT NULL AND applied_promotion_benefit_type IS NOT NULL)
            OR
            (line_kind IN ('OPEN_SALE', 'MANUAL_PRICED_LINE')
                AND NOT external_historical
                AND source_cart_item_id IS NULL
                AND source_menu_item_id IS NULL
                AND applied_promotion_id IS NULL
                AND applied_promotion_name IS NULL
                AND applied_promotion_benefit_type IS NULL)
        );
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_reward_shape_check
        CHECK (
            (line_kind IN ('PAID', 'OPEN_SALE', 'MANUAL_PRICED_LINE')
                AND source_paid_line_id IS NULL AND reward_ordinal IS NULL)
            OR
            (line_kind = 'PROMOTION_REWARD' AND source_paid_line_id IS NOT NULL AND reward_ordinal > 0)
        );
ALTER TABLE public.order_lines ADD CONSTRAINT order_lines_manual_client_line_key_check
        CHECK (
            (line_kind = 'PAID' AND source_menu_item_id IS NOT NULL
                AND client_line_key IS NOT NULL AND trim(client_line_key) <> '')
            OR
            (line_kind = 'PAID' AND source_menu_item_id IS NULL AND client_line_key IS NULL)
            OR
            (line_kind = 'MANUAL_PRICED_LINE'
                AND client_line_key IS NOT NULL AND trim(client_line_key) <> '')
            OR
            (line_kind IN ('PROMOTION_REWARD', 'OPEN_SALE') AND client_line_key IS NULL)
        );

ALTER TABLE public.order_line_selection_snapshots ADD COLUMN selection_note varchar(500);
ALTER TABLE public.order_line_selection_snapshots ADD CONSTRAINT order_line_selection_snapshots_note_not_blank_check
        CHECK (selection_note IS NULL OR trim(selection_note) <> '');

CREATE TABLE public.order_line_selection_component_omissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    selection_snapshot_id bigint NOT NULL,
    source_component_id bigint NOT NULL,
    component_code varchar(80) NOT NULL,
    component_name varchar(160) NOT NULL,
    component_detail varchar(160),
    component_display_order integer NOT NULL,
    CONSTRAINT order_line_selection_component_omissions_pkey PRIMARY KEY (id),
    CONSTRAINT order_line_selection_component_omissions_selection_snapshot_fkey
        FOREIGN KEY (selection_snapshot_id) REFERENCES public.order_line_selection_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT order_line_selection_component_omissions_source_component_positive_check CHECK (source_component_id > 0),
    CONSTRAINT order_line_selection_component_omissions_code_not_blank_check CHECK (trim(component_code) <> ''),
    CONSTRAINT order_line_selection_component_omissions_name_not_blank_check CHECK (trim(component_name) <> ''),
    CONSTRAINT order_line_selection_component_omissions_detail_not_blank_check
        CHECK (component_detail IS NULL OR trim(component_detail) <> ''),
    CONSTRAINT order_line_selection_component_omissions_display_order_check CHECK (component_display_order >= 0),
    CONSTRAINT order_line_selection_component_omissions_selection_component_key
        UNIQUE (selection_snapshot_id, source_component_id)
);

CREATE INDEX order_line_selection_component_omissions_selection_idx
    ON public.order_line_selection_component_omissions (selection_snapshot_id, component_display_order, id);

INSERT INTO public.catalog_bootstrap_rule_sets (rule_set_id, applied_at)
VALUES ('SUSHIMEI_OPTIONAL_TOPPINGS_V1', NULL);
