ALTER TABLE app_users ADD COLUMN email VARCHAR(254);
ALTER TABLE app_users ADD COLUMN email_verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE app_users ADD COLUMN registration_state VARCHAR(40) NOT NULL DEFAULT 'LEGACY';

ALTER TABLE app_users ADD CONSTRAINT app_users_email_normalized_check
    CHECK (email IS NULL OR (trim(email) <> '' AND email = lower(trim(email))));
ALTER TABLE app_users ADD CONSTRAINT app_users_email_verification_consistency_check
    CHECK (email_verified_at IS NULL OR email IS NOT NULL);
ALTER TABLE app_users ADD CONSTRAINT app_users_registration_state_check
    CHECK (registration_state IN ('LEGACY', 'PENDING_EMAIL_VERIFICATION', 'ACTIVE'));

ALTER TABLE app_users
    ADD CONSTRAINT app_users_email_key UNIQUE (email);

CREATE TABLE businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT businesses_pkey PRIMARY KEY (id),
    CONSTRAINT businesses_name_not_blank_check CHECK (trim(name) <> ''),
    CONSTRAINT businesses_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT businesses_updated_at_not_before_created_at_check CHECK (updated_at >= created_at)
);

CREATE INDEX businesses_name_idx ON businesses (name);

CREATE TABLE business_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    business_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT business_memberships_pkey PRIMARY KEY (id),
    CONSTRAINT business_memberships_user_business_key UNIQUE (user_id, business_id),
    CONSTRAINT business_memberships_id_user_key UNIQUE (id, user_id),
    CONSTRAINT business_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT business_memberships_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id),
    CONSTRAINT business_memberships_role_check CHECK (role IN ('OWNER', 'MANAGER', 'CASHIER', 'KITCHEN')),
    CONSTRAINT business_memberships_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT business_memberships_updated_at_not_before_created_at_check CHECK (updated_at >= created_at)
);

CREATE INDEX business_memberships_business_id_idx ON business_memberships (business_id);

INSERT INTO businesses (name, active, created_at, updated_at, version)
SELECT 'Sushi Mei', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
WHERE NOT EXISTS (SELECT 1 FROM businesses WHERE name = 'Sushi Mei');

INSERT INTO business_memberships (user_id, business_id, role, created_at, updated_at, version)
SELECT u.id, b.id, u.role, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
FROM app_users u
CROSS JOIN businesses b
WHERE b.name = 'Sushi Mei'
  AND NOT EXISTS (
      SELECT 1 FROM business_memberships m
      WHERE m.user_id = u.id AND m.business_id = b.id
  );

ALTER TABLE auth_sessions
    ADD COLUMN active_membership_id BIGINT;

UPDATE auth_sessions s
SET active_membership_id = (
    SELECT m.id FROM business_memberships m
    WHERE m.user_id = s.user_id
      AND m.business_id = (SELECT id FROM businesses WHERE name = 'Sushi Mei')
);

ALTER TABLE auth_sessions ALTER COLUMN active_membership_id SET NOT NULL;
ALTER TABLE auth_sessions ADD CONSTRAINT auth_sessions_active_membership_user_fkey
    FOREIGN KEY (active_membership_id, user_id)
    REFERENCES business_memberships (id, user_id);

CREATE INDEX auth_sessions_active_membership_id_idx ON auth_sessions (active_membership_id);
