ALTER TABLE app_users ALTER COLUMN username VARCHAR(254);

CREATE TABLE user_terms_acceptances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    terms_version VARCHAR(64) NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    client_ip VARCHAR(64),
    CONSTRAINT user_terms_acceptances_pkey PRIMARY KEY (id),
    CONSTRAINT user_terms_acceptances_user_version_key UNIQUE (user_id, terms_version),
    CONSTRAINT user_terms_acceptances_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT user_terms_acceptances_version_not_blank_check CHECK (trim(terms_version) <> '')
);

CREATE INDEX user_terms_acceptances_user_accepted_at_idx
    ON user_terms_acceptances (user_id, accepted_at, id);

CREATE TABLE registration_rate_limit_buckets (
    bucket_key VARCHAR(64) NOT NULL,
    window_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    attempt_count INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT registration_rate_limit_buckets_pkey PRIMARY KEY (bucket_key),
    CONSTRAINT registration_rate_limit_buckets_key_length_check CHECK (char_length(bucket_key) = 64),
    CONSTRAINT registration_rate_limit_buckets_attempt_count_positive_check CHECK (attempt_count > 0),
    CONSTRAINT registration_rate_limit_buckets_updated_not_before_window_check CHECK (updated_at >= window_started_at)
);
