ALTER TABLE public.orders ADD COLUMN source_cart_id bigint;
ALTER TABLE public.orders ADD COLUMN order_source varchar(32);
ALTER TABLE public.orders ADD COLUMN fulfillment_type varchar(16);
ALTER TABLE public.orders ADD COLUMN payment_method varchar(16);
ALTER TABLE public.orders ADD COLUMN pickup_name varchar(120);
ALTER TABLE public.orders ADD COLUMN cash_denomination numeric(19,2);

ALTER TABLE public.orders
    ALTER COLUMN transfer_receipt_path SET DATA TYPE varchar(1024);

ALTER TABLE public.orders ADD CONSTRAINT orders_source_cart_id_key UNIQUE (source_cart_id);
ALTER TABLE public.orders ADD CONSTRAINT orders_order_source_check
    CHECK (order_source IS NULL OR order_source IN ('WHATSAPP_AI', 'ANDROID_MANUAL', 'COUNTER'));
ALTER TABLE public.orders ADD CONSTRAINT orders_fulfillment_type_check
    CHECK (fulfillment_type IS NULL OR fulfillment_type IN ('DELIVERY', 'PICKUP'));
ALTER TABLE public.orders ADD CONSTRAINT orders_payment_method_check
    CHECK (payment_method IS NULL OR payment_method IN ('CASH', 'TRANSFER', 'CARD'));
ALTER TABLE public.orders ADD CONSTRAINT orders_cash_denomination_positive_check
    CHECK (cash_denomination IS NULL OR cash_denomination > 0);

CREATE TABLE public.order_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id bigint NOT NULL,
    source_cart_item_id bigint NOT NULL,
    line_position integer NOT NULL,
    dish_name varchar(255) NOT NULL,
    quantity integer NOT NULL,
    unit_price_amount numeric(19,2) NOT NULL,
    line_total_amount numeric(19,2) NOT NULL,
    CONSTRAINT order_lines_pkey PRIMARY KEY (id),
    CONSTRAINT order_lines_quantity_positive_check CHECK (quantity > 0),
    CONSTRAINT order_lines_line_position_positive_check CHECK (line_position > 0),
    CONSTRAINT order_lines_unit_price_amount_positive_check CHECK (unit_price_amount > 0),
    CONSTRAINT order_lines_line_total_amount_positive_check CHECK (line_total_amount > 0),
    CONSTRAINT order_lines_line_total_amount_matches_check
        CHECK (line_total_amount = quantity * unit_price_amount),
    CONSTRAINT order_lines_order_line_position_key UNIQUE (order_id, line_position),
    CONSTRAINT order_lines_order_source_cart_item_key UNIQUE (order_id, source_cart_item_id),
    CONSTRAINT order_lines_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
