ALTER TABLE public.menu_items
    ADD COLUMN standalone_orderable boolean;

UPDATE public.menu_items
SET standalone_orderable = true
WHERE standalone_orderable IS NULL;

ALTER TABLE public.menu_items
    ALTER COLUMN standalone_orderable SET NOT NULL;

CREATE TABLE public.catalog_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(64) NOT NULL,
    name varchar(120) NOT NULL,
    active boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT catalog_tags_pkey PRIMARY KEY (id),
    CONSTRAINT catalog_tags_code_not_blank_check CHECK (trim(code) <> ''),
    CONSTRAINT catalog_tags_code_uppercase_check CHECK (code = upper(trim(code))),
    CONSTRAINT catalog_tags_code_key UNIQUE (code),
    CONSTRAINT catalog_tags_name_not_blank_check CHECK (trim(name) <> ''),
    CONSTRAINT catalog_tags_display_order_nonnegative_check CHECK (display_order >= 0),
    CONSTRAINT catalog_tags_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT catalog_tags_updated_at_not_before_created_at_check CHECK (updated_at >= created_at)
);

CREATE TABLE public.menu_item_tags (
    menu_item_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    CONSTRAINT menu_item_tags_pkey PRIMARY KEY (menu_item_id, tag_id),
    CONSTRAINT menu_item_tags_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
    CONSTRAINT menu_item_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.catalog_tags(id)
);

CREATE INDEX menu_item_tags_tag_id_menu_item_id_idx
    ON public.menu_item_tags (tag_id, menu_item_id);

CREATE TABLE public.menu_selection_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_menu_item_id bigint NOT NULL,
    name varchar(160) NOT NULL,
    min_selections integer NOT NULL,
    max_selections integer NOT NULL,
    allow_duplicates boolean NOT NULL,
    display_order integer NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT menu_selection_groups_pkey PRIMARY KEY (id),
    CONSTRAINT menu_selection_groups_parent_menu_item_id_fkey FOREIGN KEY (parent_menu_item_id) REFERENCES public.menu_items(id),
    CONSTRAINT menu_selection_groups_name_not_blank_check CHECK (trim(name) <> ''),
    CONSTRAINT menu_selection_groups_min_selections_nonnegative_check CHECK (min_selections >= 0),
    CONSTRAINT menu_selection_groups_max_selections_positive_check CHECK (max_selections > 0),
    CONSTRAINT menu_selection_groups_selection_range_check CHECK (max_selections >= min_selections),
    CONSTRAINT menu_selection_groups_display_order_nonnegative_check CHECK (display_order >= 0),
    CONSTRAINT menu_selection_groups_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT menu_selection_groups_updated_at_not_before_created_at_check CHECK (updated_at >= created_at)
);

CREATE INDEX menu_selection_groups_parent_active_display_order_id_idx
    ON public.menu_selection_groups (parent_menu_item_id, active, display_order, id);

CREATE TABLE public.menu_selection_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    selection_group_id bigint NOT NULL,
    target_menu_item_id bigint,
    target_tag_id bigint,
    pricing_policy varchar(32) NOT NULL,
    reference_price_amount numeric(19,2),
    fixed_surcharge_amount numeric(19,2),
    priority integer NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT menu_selection_rules_pkey PRIMARY KEY (id),
    CONSTRAINT menu_selection_rules_selection_group_id_fkey FOREIGN KEY (selection_group_id) REFERENCES public.menu_selection_groups(id),
    CONSTRAINT menu_selection_rules_target_menu_item_id_fkey FOREIGN KEY (target_menu_item_id) REFERENCES public.menu_items(id),
    CONSTRAINT menu_selection_rules_target_tag_id_fkey FOREIGN KEY (target_tag_id) REFERENCES public.catalog_tags(id),
    CONSTRAINT menu_selection_rules_target_xor_check CHECK (
        (target_menu_item_id IS NOT NULL AND target_tag_id IS NULL)
        OR (target_menu_item_id IS NULL AND target_tag_id IS NOT NULL)
    ),
    CONSTRAINT menu_selection_rules_pricing_policy_check CHECK (
        pricing_policy IN ('INCLUDED', 'PRICE_DIFFERENCE', 'FULL_ITEM_PRICE', 'FIXED_SURCHARGE')
    ),
    CONSTRAINT menu_selection_rules_price_parameters_check CHECK (
        (pricing_policy IN ('INCLUDED', 'FULL_ITEM_PRICE')
            AND reference_price_amount IS NULL
            AND fixed_surcharge_amount IS NULL)
        OR (pricing_policy = 'PRICE_DIFFERENCE'
            AND reference_price_amount IS NOT NULL
            AND reference_price_amount > 0
            AND fixed_surcharge_amount IS NULL)
        OR (pricing_policy = 'FIXED_SURCHARGE'
            AND reference_price_amount IS NULL
            AND fixed_surcharge_amount IS NOT NULL
            AND fixed_surcharge_amount >= 0)
    ),
    CONSTRAINT menu_selection_rules_priority_nonnegative_check CHECK (priority >= 0),
    CONSTRAINT menu_selection_rules_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT menu_selection_rules_updated_at_not_before_created_at_check CHECK (updated_at >= created_at)
);

CREATE INDEX menu_selection_rules_group_active_priority_id_idx
    ON public.menu_selection_rules (selection_group_id, active, priority DESC, id);
