package com.sushimei.sushimei.backend.security;

public enum SecurityAuditEventType {
    LOGIN_SUCCESS, LOGIN_FAILURE, REFRESH_SUCCESS, REFRESH_FAILURE, REFRESH_REPLAY_DETECTED,
    LOGOUT, SESSION_REVOKED, USER_CREATED, USER_UPDATED, USER_DISABLED, PASSWORD_CHANGED, PASSWORD_RESET
}