package com.sushimei.sushimei.backend.businessday;

public enum BusinessDayError {
    BUSINESS_DAY_INVALID,
    BUSINESS_DAY_ALREADY_OPEN,
    BUSINESS_DAY_ALREADY_CLOSED,
    BUSINESS_DAY_CLOSED,
    BUSINESS_DAY_HAS_ACTIVE_ORDERS,
    BUSINESS_DAY_NOT_OPEN,
    BUSINESS_DAY_OPEN_REQUIRED,
    BUSINESS_DAY_NOT_CLOSED,
    BUSINESS_DAY_REOPEN_NOT_ALLOWED,
    BUSINESS_DAY_CASH_EXPENSE_IDEMPOTENCY_CONFLICT,
    BUSINESS_DAY_CASH_EXPENSES_EXCEED_AVAILABLE_CASH
}
