package com.sushimei.sushimei.backend.businessday;

public enum BusinessDayError {
    BUSINESS_DAY_INVALID,
    BUSINESS_DAY_ALREADY_OPEN,
    BUSINESS_DAY_ALREADY_CLOSED,
    BUSINESS_DAY_CLOSED,
    BUSINESS_DAY_HAS_ACTIVE_ORDERS,
    BUSINESS_DAY_NOT_OPEN,
    BUSINESS_DAY_NOT_CLOSED,
    BUSINESS_DAY_REOPEN_NOT_ALLOWED
}
