CREATE TABLE public.cart (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.cart_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    phone_number character varying(255),
    status character varying(255),
    CONSTRAINT cart_pkey PRIMARY KEY (id)
);

CREATE TABLE public.cart_items (
    quantity integer,
    unit_price double precision,
    cart_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.cart_items_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    dish_name character varying(255),
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE public.carts (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.carts_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    status character varying(255),
    CONSTRAINT carts_pkey PRIMARY KEY (id)
);

CREATE TABLE public.conversation_sessions (
    phone_number character varying(32) NOT NULL,
    cash_denomination numeric(19,2),
    created_at timestamp(6) with time zone NOT NULL,
    delivery_address character varying(500),
    fulfillment_type character varying(16),
    last_activity_at timestamp(6) with time zone NOT NULL,
    payment_method character varying(16),
    pickup_name character varying(120),
    state character varying(48) NOT NULL,
    transfer_receipt_path character varying(1024),
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT conversation_sessions_pkey PRIMARY KEY (phone_number),
    CONSTRAINT conversation_sessions_fulfillment_type_check
        CHECK ((fulfillment_type)::text = ANY ((ARRAY['DELIVERY'::character varying, 'PICKUP'::character varying])::text[])),
    CONSTRAINT conversation_sessions_payment_method_check
        CHECK ((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'TRANSFER'::character varying, 'CARD'::character varying])::text[])),
    CONSTRAINT conversation_sessions_state_check
        CHECK ((state)::text = ANY ((ARRAY[
            'ORDERING'::character varying,
            'WAITING_CART_CONFIRMATION'::character varying,
            'WAITING_FULFILLMENT_TYPE'::character varying,
            'WAITING_DELIVERY_ADDRESS'::character varying,
            'WAITING_PICKUP_NAME'::character varying,
            'WAITING_PAYMENT_METHOD'::character varying,
            'WAITING_CASH_DENOMINATION'::character varying,
            'WAITING_TRANSFER_RECEIPT'::character varying,
            'READY_TO_CONFIRM'::character varying,
            'ORDER_CONFIRMED'::character varying,
            'CANCELLED'::character varying
        ])::text[]))
);

CREATE TABLE public.orders (
    total_amount double precision,
    created_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.orders_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    delivery_address character varying(500),
    delivery_type character varying(255),
    order_details text,
    payment_notes character varying(255),
    phone_number character varying(255),
    status character varying(255),
    transfer_receipt_path character varying(255),
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk99e0am9jpriwxcm6is7xfedy3
    FOREIGN KEY (cart_id) REFERENCES public.cart(id);
