ALTER TABLE public.business_days
    ADD COLUMN reopened_at timestamp with time zone,
    ADD COLUMN reopened_by_user_id bigint,
    ADD COLUMN reopen_count integer NOT NULL DEFAULT 0,
    ADD CONSTRAINT business_days_reopened_by_user_id_fkey
        FOREIGN KEY (reopened_by_user_id) REFERENCES public.app_users(id),
    ADD CONSTRAINT business_days_reopen_count_nonnegative_check CHECK (reopen_count >= 0),
    ADD CONSTRAINT business_days_reopen_metadata_check CHECK (
        (reopen_count = 0 AND reopened_at IS NULL AND reopened_by_user_id IS NULL)
        OR (reopen_count > 0 AND reopened_at IS NOT NULL AND reopened_by_user_id IS NOT NULL)
    );

CREATE TABLE public.business_day_closures (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_day_id bigint NOT NULL,
    close_number integer NOT NULL,
    closed_at timestamp with time zone NOT NULL,
    closed_by_user_id bigint NOT NULL,
    opening_cash_amount numeric(19,2) NOT NULL,
    completed_sales_amount numeric(19,2) NOT NULL,
    cash_sales_amount numeric(19,2) NOT NULL,
    transfer_sales_amount numeric(19,2) NOT NULL,
    card_sales_amount numeric(19,2) NOT NULL,
    unclassified_sales_amount numeric(19,2) NOT NULL,
    completed_order_count bigint NOT NULL,
    voided_order_count bigint NOT NULL,
    expected_closing_cash_amount numeric(19,2) NOT NULL,
    actual_closing_cash_amount numeric(19,2) NOT NULL,
    cash_difference_amount numeric(19,2) NOT NULL,
    CONSTRAINT business_day_closures_pkey PRIMARY KEY (id),
    CONSTRAINT business_day_closures_business_day_number_key UNIQUE (business_day_id, close_number),
    CONSTRAINT business_day_closures_business_day_id_fkey
        FOREIGN KEY (business_day_id) REFERENCES public.business_days(id),
    CONSTRAINT business_day_closures_closed_by_user_id_fkey
        FOREIGN KEY (closed_by_user_id) REFERENCES public.app_users(id),
    CONSTRAINT business_day_closures_close_number_positive_check CHECK (close_number > 0),
    CONSTRAINT business_day_closures_money_nonnegative_check CHECK (
        opening_cash_amount >= 0
        AND completed_sales_amount >= 0
        AND cash_sales_amount >= 0
        AND transfer_sales_amount >= 0
        AND card_sales_amount >= 0
        AND unclassified_sales_amount >= 0
        AND expected_closing_cash_amount >= 0
        AND actual_closing_cash_amount >= 0
    ),
    CONSTRAINT business_day_closures_order_counts_nonnegative_check CHECK (
        completed_order_count >= 0 AND voided_order_count >= 0
    ),
    CONSTRAINT business_day_closures_snapshot_reconciliation_check CHECK (
        completed_sales_amount = cash_sales_amount + transfer_sales_amount
            + card_sales_amount + unclassified_sales_amount
        AND expected_closing_cash_amount = opening_cash_amount + cash_sales_amount
        AND cash_difference_amount = actual_closing_cash_amount - expected_closing_cash_amount
    )
);

CREATE INDEX business_day_closures_business_day_id_close_number_idx
    ON public.business_day_closures (business_day_id, close_number);

INSERT INTO public.business_day_closures (
    business_day_id, close_number, closed_at, closed_by_user_id,
    opening_cash_amount, completed_sales_amount, cash_sales_amount,
    transfer_sales_amount, card_sales_amount, unclassified_sales_amount,
    completed_order_count, voided_order_count, expected_closing_cash_amount,
    actual_closing_cash_amount, cash_difference_amount
)
SELECT
    id, 1, closed_at, closed_by_user_id,
    opening_cash_amount, completed_sales_amount, cash_sales_amount,
    transfer_sales_amount, card_sales_amount, unclassified_sales_amount,
    completed_order_count, voided_order_count, expected_closing_cash_amount,
    actual_closing_cash_amount, cash_difference_amount
FROM public.business_days
WHERE status = 'CLOSED';
