ALTER TABLE public.order_lines
    ADD COLUMN line_note varchar(500);

ALTER TABLE public.order_lines
    DROP CONSTRAINT order_lines_line_kind_check,
    DROP CONSTRAINT order_lines_money_by_kind_check,
    DROP CONSTRAINT order_lines_provenance_check,
    DROP CONSTRAINT order_lines_reward_shape_check,
    DROP CONSTRAINT order_lines_manual_client_line_key_check,
    ADD CONSTRAINT order_lines_line_kind_check
        CHECK (line_kind IN ('PAID', 'PROMOTION_REWARD', 'OPEN_SALE')),
    ADD CONSTRAINT order_lines_money_by_kind_check
        CHECK (
            (external_historical AND line_kind = 'PAID'
                AND unit_price_amount >= 0 AND line_total_amount >= 0)
            OR
            (NOT external_historical AND line_kind IN ('PAID', 'OPEN_SALE')
                AND unit_price_amount > 0 AND line_total_amount > 0)
            OR
            (NOT external_historical AND line_kind = 'PROMOTION_REWARD'
                AND unit_price_amount >= 0 AND line_total_amount >= 0)
        ),
    ADD CONSTRAINT order_lines_provenance_check
        CHECK (
            (line_kind = 'PAID' AND (
                source_cart_item_id IS NOT NULL
                OR source_menu_item_id IS NOT NULL
                OR (external_product_reference IS NOT NULL AND btrim(external_product_reference) <> '')
                OR external_historical
            ))
            OR
            (line_kind = 'PROMOTION_REWARD'
                AND applied_promotion_id IS NOT NULL AND applied_promotion_benefit_type IS NOT NULL)
            OR
            (line_kind = 'OPEN_SALE'
                AND NOT external_historical
                AND source_cart_item_id IS NULL
                AND source_menu_item_id IS NULL
                AND applied_promotion_id IS NULL
                AND applied_promotion_name IS NULL
                AND applied_promotion_benefit_type IS NULL)
        ),
    ADD CONSTRAINT order_lines_reward_shape_check
        CHECK (
            (line_kind IN ('PAID', 'OPEN_SALE') AND source_paid_line_id IS NULL AND reward_ordinal IS NULL)
            OR
            (line_kind = 'PROMOTION_REWARD' AND source_paid_line_id IS NOT NULL AND reward_ordinal > 0)
        ),
    ADD CONSTRAINT order_lines_manual_client_line_key_check
        CHECK (
            (line_kind = 'PAID' AND source_menu_item_id IS NOT NULL
                AND client_line_key IS NOT NULL AND btrim(client_line_key) <> '')
            OR
            (line_kind = 'PAID' AND source_menu_item_id IS NULL AND client_line_key IS NULL)
            OR
            (line_kind IN ('PROMOTION_REWARD', 'OPEN_SALE') AND client_line_key IS NULL)
        ),
    ADD CONSTRAINT order_lines_line_note_not_blank_check
        CHECK (line_note IS NULL OR btrim(line_note) <> '');

CREATE TABLE public.menu_item_default_components (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_item_id bigint NOT NULL,
    component_code varchar(80) NOT NULL,
    display_name varchar(160) NOT NULL,
    component_detail varchar(160),
    included_by_default boolean NOT NULL,
    removable boolean NOT NULL,
    display_order integer NOT NULL,
    active boolean NOT NULL,
    CONSTRAINT menu_item_default_components_pkey PRIMARY KEY (id),
    CONSTRAINT menu_item_default_components_menu_item_fkey
        FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
    CONSTRAINT menu_item_default_components_code_not_blank_check CHECK (btrim(component_code) <> ''),
    CONSTRAINT menu_item_default_components_name_not_blank_check CHECK (btrim(display_name) <> ''),
    CONSTRAINT menu_item_default_components_detail_not_blank_check
        CHECK (component_detail IS NULL OR btrim(component_detail) <> ''),
    CONSTRAINT menu_item_default_components_display_order_check CHECK (display_order >= 0),
    CONSTRAINT menu_item_default_components_menu_item_code_key UNIQUE (menu_item_id, component_code)
);

CREATE INDEX menu_item_default_components_menu_item_active_idx
    ON public.menu_item_default_components (menu_item_id, active, display_order, id);

CREATE TABLE public.order_line_component_omissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_line_id bigint NOT NULL,
    source_component_id bigint NOT NULL,
    component_code varchar(80) NOT NULL,
    component_name varchar(160) NOT NULL,
    component_detail varchar(160),
    component_display_order integer NOT NULL,
    CONSTRAINT order_line_component_omissions_pkey PRIMARY KEY (id),
    CONSTRAINT order_line_component_omissions_order_line_fkey
        FOREIGN KEY (order_line_id) REFERENCES public.order_lines(id),
    CONSTRAINT order_line_component_omissions_source_component_positive_check CHECK (source_component_id > 0),
    CONSTRAINT order_line_component_omissions_code_not_blank_check CHECK (btrim(component_code) <> ''),
    CONSTRAINT order_line_component_omissions_name_not_blank_check CHECK (btrim(component_name) <> ''),
    CONSTRAINT order_line_component_omissions_detail_not_blank_check
        CHECK (component_detail IS NULL OR btrim(component_detail) <> ''),
    CONSTRAINT order_line_component_omissions_display_order_check CHECK (component_display_order >= 0),
    CONSTRAINT order_line_component_omissions_order_component_key UNIQUE (order_line_id, source_component_id)
);

CREATE INDEX order_line_component_omissions_order_line_idx
    ON public.order_line_component_omissions (order_line_id, component_display_order, id);

INSERT INTO public.catalog_bootstrap_rule_sets (rule_set_id, applied_at)
VALUES ('SUSHIMEI_ITEM_COMPONENTS_V1', NULL);
