CREATE TABLE public.business_day_cash_expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_day_id bigint NOT NULL,
    client_request_id uuid NOT NULL,
    request_fingerprint varchar(64) NOT NULL,
    amount numeric(19,2) NOT NULL,
    description varchar(500) NOT NULL,
    note varchar(500),
    created_at timestamp with time zone NOT NULL,
    created_by_user_id bigint NOT NULL,
    CONSTRAINT business_day_cash_expenses_pkey PRIMARY KEY (id),
    CONSTRAINT business_day_cash_expenses_client_request_id_key UNIQUE (client_request_id),
    CONSTRAINT business_day_cash_expenses_business_day_id_fkey
        FOREIGN KEY (business_day_id) REFERENCES public.business_days(id),
    CONSTRAINT business_day_cash_expenses_created_by_user_id_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES public.app_users(id),
    CONSTRAINT business_day_cash_expenses_amount_positive_check CHECK (amount > 0),
    CONSTRAINT business_day_cash_expenses_description_not_blank_check CHECK (btrim(description) <> ''),
    CONSTRAINT business_day_cash_expenses_note_not_blank_check CHECK (note IS NULL OR btrim(note) <> ''),
    CONSTRAINT business_day_cash_expenses_fingerprint_not_blank_check CHECK (btrim(request_fingerprint) <> '')
);

CREATE INDEX business_day_cash_expenses_business_day_created_idx
    ON public.business_day_cash_expenses (business_day_id, created_at, id);

ALTER TABLE public.business_days
    ADD COLUMN cash_expense_amount numeric(19,2),
    ADD COLUMN cash_expense_count bigint;

UPDATE public.business_days
SET cash_expense_amount = 0.00,
    cash_expense_count = 0
WHERE status = 'CLOSED';

ALTER TABLE public.business_days
    DROP CONSTRAINT business_days_close_snapshot_check,
    ADD CONSTRAINT business_days_close_snapshot_check CHECK (
        (status = 'OPEN'
            AND completed_sales_amount IS NULL
            AND cash_sales_amount IS NULL
            AND cash_expense_amount IS NULL
            AND cash_expense_count IS NULL
            AND transfer_sales_amount IS NULL
            AND card_sales_amount IS NULL
            AND unclassified_sales_amount IS NULL
            AND completed_order_count IS NULL
            AND voided_order_count IS NULL
            AND expected_closing_cash_amount IS NULL
            AND actual_closing_cash_amount IS NULL
            AND cash_difference_amount IS NULL
            AND closed_at IS NULL
            AND closed_by_user_id IS NULL)
        OR
        (status = 'CLOSED'
            AND completed_sales_amount IS NOT NULL AND completed_sales_amount >= 0
            AND cash_sales_amount IS NOT NULL AND cash_sales_amount >= 0
            AND cash_expense_amount IS NOT NULL AND cash_expense_amount >= 0
            AND cash_expense_count IS NOT NULL AND cash_expense_count >= 0
            AND transfer_sales_amount IS NOT NULL AND transfer_sales_amount >= 0
            AND card_sales_amount IS NOT NULL AND card_sales_amount >= 0
            AND unclassified_sales_amount IS NOT NULL AND unclassified_sales_amount >= 0
            AND completed_order_count IS NOT NULL AND completed_order_count >= 0
            AND voided_order_count IS NOT NULL AND voided_order_count >= 0
            AND expected_closing_cash_amount IS NOT NULL AND expected_closing_cash_amount >= 0
            AND actual_closing_cash_amount IS NOT NULL AND actual_closing_cash_amount >= 0
            AND cash_difference_amount IS NOT NULL
            AND closed_at IS NOT NULL
            AND closed_by_user_id IS NOT NULL
            AND completed_sales_amount = cash_sales_amount + transfer_sales_amount
                + card_sales_amount + unclassified_sales_amount
            AND expected_closing_cash_amount = opening_cash_amount + cash_sales_amount - cash_expense_amount
            AND cash_difference_amount = actual_closing_cash_amount - expected_closing_cash_amount
            AND closed_at >= opened_at)
    );

ALTER TABLE public.business_day_closures
    ADD COLUMN cash_expense_amount numeric(19,2),
    ADD COLUMN cash_expense_count bigint;

UPDATE public.business_day_closures
SET cash_expense_amount = 0.00,
    cash_expense_count = 0
WHERE cash_expense_amount IS NULL OR cash_expense_count IS NULL;

ALTER TABLE public.business_day_closures
    ALTER COLUMN cash_expense_amount SET NOT NULL,
    ALTER COLUMN cash_expense_count SET NOT NULL,
    DROP CONSTRAINT business_day_closures_snapshot_reconciliation_check,
    ADD CONSTRAINT business_day_closures_snapshot_reconciliation_check CHECK (
        completed_sales_amount = cash_sales_amount + transfer_sales_amount
            + card_sales_amount + unclassified_sales_amount
        AND expected_closing_cash_amount = opening_cash_amount + cash_sales_amount - cash_expense_amount
        AND cash_difference_amount = actual_closing_cash_amount - expected_closing_cash_amount
    ),
    ADD CONSTRAINT business_day_closures_cash_expense_nonnegative_check CHECK (
        cash_expense_amount >= 0 AND cash_expense_count >= 0
    );
