CREATE TABLE public.email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT email_verification_tokens_token_hash_key UNIQUE (token_hash),
    CONSTRAINT email_verification_tokens_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE,
    CONSTRAINT email_verification_tokens_hash_length_check CHECK (char_length(token_hash) = 64),
    CONSTRAINT email_verification_tokens_expiry_after_creation_check CHECK (expires_at > created_at),
    CONSTRAINT email_verification_tokens_used_after_creation_check CHECK (used_at IS NULL OR used_at >= created_at),
    CONSTRAINT email_verification_tokens_revoked_after_creation_check CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CONSTRAINT email_verification_tokens_not_used_and_revoked_check CHECK (used_at IS NULL OR revoked_at IS NULL)
);

CREATE INDEX email_verification_tokens_user_active_idx
    ON public.email_verification_tokens (user_id, created_at DESC, id)
    WHERE used_at IS NULL AND revoked_at IS NULL;
