CREATE TABLE public.menu_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(160) NOT NULL,
    description varchar(1000),
    category varchar(120) NOT NULL,
    price_amount numeric(19,2) NOT NULL,
    active boolean NOT NULL,
    available boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT menu_items_pkey PRIMARY KEY (id),
    CONSTRAINT menu_items_name_not_blank_check CHECK (btrim(name) <> ''),
    CONSTRAINT menu_items_category_not_blank_check CHECK (btrim(category) <> ''),
    CONSTRAINT menu_items_price_amount_positive_check CHECK (price_amount > 0),
    CONSTRAINT menu_items_display_order_nonnegative_check CHECK (display_order >= 0),
    CONSTRAINT menu_items_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT menu_items_updated_at_not_before_created_at_check CHECK (updated_at >= created_at)
);

CREATE INDEX menu_items_active_category_display_order_name_id_idx
    ON public.menu_items (active, category, display_order, name, id);
