CREATE TABLE public.promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(160) NOT NULL,
    active boolean NOT NULL,
    priority integer NOT NULL,
    benefit_type varchar(32) NOT NULL,
    fixed_unit_price_amount numeric(19,2),
    buy_quantity integer,
    reward_quantity integer,
    repeat_enabled boolean,
    valid_from date,
    valid_until date,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT promotions_pkey PRIMARY KEY (id),
    CONSTRAINT promotions_name_not_blank_check CHECK (btrim(name) <> ''),
    CONSTRAINT promotions_priority_nonnegative_check CHECK (priority >= 0),
    CONSTRAINT promotions_benefit_type_check CHECK (benefit_type IN ('FIXED_UNIT_PRICE', 'BUY_X_GET_Y_SAME_ITEM')),
    CONSTRAINT promotions_benefit_parameters_check CHECK (
        (benefit_type = 'FIXED_UNIT_PRICE'
            AND fixed_unit_price_amount IS NOT NULL
            AND fixed_unit_price_amount > 0
            AND buy_quantity IS NULL
            AND reward_quantity IS NULL
            AND repeat_enabled IS NULL)
        OR (benefit_type = 'BUY_X_GET_Y_SAME_ITEM'
            AND fixed_unit_price_amount IS NULL
            AND buy_quantity IS NOT NULL
            AND buy_quantity > 0
            AND reward_quantity IS NOT NULL
            AND reward_quantity > 0
            AND repeat_enabled IS NOT NULL)
    ),
    CONSTRAINT promotions_valid_date_range_check CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from),
    CONSTRAINT promotions_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT promotions_updated_at_not_before_created_at_check CHECK (updated_at >= created_at)
);

CREATE INDEX promotions_active_priority_id_idx ON public.promotions (active, priority DESC, id);

CREATE TABLE public.promotion_weekdays (
    promotion_id bigint NOT NULL,
    iso_day_of_week integer NOT NULL,
    CONSTRAINT promotion_weekdays_pkey PRIMARY KEY (promotion_id, iso_day_of_week),
    CONSTRAINT promotion_weekdays_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
    CONSTRAINT promotion_weekdays_iso_day_of_week_check CHECK (iso_day_of_week BETWEEN 1 AND 7)
);

CREATE TABLE public.promotion_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    promotion_id bigint NOT NULL,
    target_menu_item_id bigint,
    target_tag_id bigint,
    CONSTRAINT promotion_targets_pkey PRIMARY KEY (id),
    CONSTRAINT promotion_targets_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
    CONSTRAINT promotion_targets_target_menu_item_id_fkey FOREIGN KEY (target_menu_item_id) REFERENCES public.menu_items(id),
    CONSTRAINT promotion_targets_target_tag_id_fkey FOREIGN KEY (target_tag_id) REFERENCES public.catalog_tags(id),
    CONSTRAINT promotion_targets_target_xor_check CHECK (
        (target_menu_item_id IS NOT NULL AND target_tag_id IS NULL)
        OR (target_menu_item_id IS NULL AND target_tag_id IS NOT NULL)
    )
);

CREATE INDEX promotion_targets_menu_item_id_idx ON public.promotion_targets (target_menu_item_id);
CREATE INDEX promotion_targets_tag_id_idx ON public.promotion_targets (target_tag_id);
