CREATE TABLE public.app_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(80) NOT NULL,
    display_name varchar(120) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role varchar(20) NOT NULL,
    active boolean NOT NULL,
    failed_login_attempts integer NOT NULL,
    locked_until timestamp(6) with time zone,
    last_login_at timestamp(6) with time zone,
    password_changed_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT app_users_pkey PRIMARY KEY (id),
    CONSTRAINT app_users_username_key UNIQUE (username),
    CONSTRAINT app_users_username_not_blank_check CHECK (btrim(username) <> ''),
    CONSTRAINT app_users_username_lowercase_check CHECK (username = lower(username)),
    CONSTRAINT app_users_display_name_not_blank_check CHECK (btrim(display_name) <> ''),
    CONSTRAINT app_users_role_check CHECK (role IN ('OWNER', 'MANAGER', 'CASHIER', 'KITCHEN')),
    CONSTRAINT app_users_failed_login_attempts_nonnegative_check CHECK (failed_login_attempts >= 0),
    CONSTRAINT app_users_version_nonnegative_check CHECK (version >= 0),
    CONSTRAINT app_users_updated_at_not_before_created_at_check CHECK (updated_at >= created_at),
    CONSTRAINT app_users_password_changed_at_not_before_created_at_check CHECK (password_changed_at >= created_at)
);

CREATE TABLE public.auth_sessions (
    id uuid NOT NULL,
    user_id bigint NOT NULL,
    device_id varchar(120) NOT NULL,
    device_name varchar(160),
    app_version varchar(40),
    current_refresh_token_hash varchar(64) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_refreshed_at timestamp(6) with time zone NOT NULL,
    absolute_expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    revoke_reason varchar(80),
    CONSTRAINT auth_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_sessions_current_refresh_token_hash_key UNIQUE (current_refresh_token_hash),
    CONSTRAINT auth_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id),
    CONSTRAINT auth_sessions_device_id_not_blank_check CHECK (btrim(device_id) <> ''),
    CONSTRAINT auth_sessions_current_refresh_token_hash_length_check CHECK (char_length(current_refresh_token_hash) = 64),
    CONSTRAINT auth_sessions_absolute_expires_after_created_check CHECK (absolute_expires_at > created_at),
    CONSTRAINT auth_sessions_last_refreshed_not_before_created_check CHECK (last_refreshed_at >= created_at),
    CONSTRAINT auth_sessions_revoked_not_before_created_check CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX auth_sessions_user_id_idx ON public.auth_sessions (user_id);
CREATE INDEX auth_sessions_user_device_idx ON public.auth_sessions (user_id, device_id);

CREATE TABLE public.auth_refresh_token_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id uuid NOT NULL,
    token_hash varchar(64) NOT NULL,
    rotated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT auth_refresh_token_history_pkey PRIMARY KEY (id),
    CONSTRAINT auth_refresh_token_history_token_hash_key UNIQUE (token_hash),
    CONSTRAINT auth_refresh_token_history_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.auth_sessions(id),
    CONSTRAINT auth_refresh_token_history_token_hash_length_check CHECK (char_length(token_hash) = 64)
);
CREATE INDEX auth_refresh_token_history_session_id_idx ON public.auth_refresh_token_history (session_id);

CREATE TABLE public.security_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type varchar(64) NOT NULL,
    actor_user_id bigint,
    subject_user_id bigint,
    session_id uuid,
    device_id varchar(120),
    client_ip varchar(64),
    outcome varchar(20) NOT NULL,
    reason_code varchar(80),
    occurred_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT security_audit_events_pkey PRIMARY KEY (id),
    CONSTRAINT security_audit_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.app_users(id),
    CONSTRAINT security_audit_events_subject_user_id_fkey FOREIGN KEY (subject_user_id) REFERENCES public.app_users(id),
    CONSTRAINT security_audit_events_outcome_check CHECK (outcome IN ('SUCCESS', 'FAILURE'))
);
CREATE INDEX security_audit_events_occurred_at_idx ON public.security_audit_events (occurred_at);
CREATE INDEX security_audit_events_actor_user_id_idx ON public.security_audit_events (actor_user_id);
CREATE INDEX security_audit_events_subject_user_id_idx ON public.security_audit_events (subject_user_id);